name: contri_app
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+112

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.7
  convex_bottom_bar: ^2.6.0
  country_codes: ^1.0.1
  cupertino_icons: ^0.1.3
  equatable: ^1.2.2
  expandable: ^4.1.4
  firebase_analytics: any
  firebase_auth: ^0.16.1
  firebase_core: any
  firebase_image: ^0.1.6
  firebase_in_app_messaging: any
  firebase_messaging: ^6.0.16
  flare_flutter: ^2.0.5
  flutter_bloc: ^5.0.1
  flutter_share: ^1.0.2+1
  flutter_sms: 2.0.0+2
  flutter_svg: any
  fluttercontactpicker: ^2.4.3
  fluttertoast: ^7.0.2
  google_sign_in: ^4.5.1
  in_app_review: ^0.2.0+4
  intl_phone_number_input: ^0.6.0
  json_annotation: ^3.1.1
  logger: ^0.9.1
  pull_to_refresh: ^1.6.1
  razorpay_flutter: ^1.2.2
  shared_preferences: ">=0.5.0 <2.0.0"
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.13
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/auth_icons/
    - assets/icons/nav_bar/
    - assets/icons/bottom_bar/
    - assets/icons/misc/
    - assets/icons/drawer_menu/
    - assets/flare/
    - assets/illustrations/
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
